---
# Source: airflow/templates/poddisruptionbudget.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: airflow-pdb
  labels:
    app: airflow
    component: scheduler
    chart: airflow-4.8.0
    release: airflow
    heritage: Helm
spec:
  selector:
    matchLabels:
      app: airflow
      component: scheduler
      release: airflow
  enabled: true
  maxUnavailable: 1
