---
# Source: airflow/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow
  labels:
    app: airflow
    chart: airflow-4.8.0
    release: airflow
    heritage: Helm
