---
# Source: airflow/charts/postgresql/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow-postgresql
  labels:
    app: postgresql
    chart: postgresql-0.13.1
    release: airflow
    heritage: Helm
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
