---
# Source: airflow/charts/redis/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: airflow-redis
  labels:
    app: redis
    chart: redis-7.0.0
    release: "airflow"
    heritage: "Helm"
type: Opaque
data:
  redis-password: "YWlyZmxvdw=="
